### ISSUE TITLE
Dependent on iPad model and size

### ISSUE THREAD

**Issue by dpentecost** [AudioKit/DrumPadPlayground#1]
Great project! Just what I was looking for. 

But on my 1st gen iPad Pro, the pad locations are off - you hit a pad and an adjacent pad (or farther) pad activates. I figured it was a screen resolution or size issue. And I see that the simulator screenshot on the repo must be from Xcode - it shows a different model iPad.

So as an iPad playgrounds app, it loads okay, but to customize it I may have to take it to Xcode and load it back as my model iPad. Haven't tried that yet.

Not sure what you can do to make it adapt to different models. But wanted to give you a heads up. Thanks!

**Comment by NickCulbertson** [comment]
Is the issue you're experiencing that the pads' touch targets don't update when the device is rotated to a new orientation?

**Comment by NickCulbertson** [comment]
In AudioKitUI in the script TapCountingDrumPadGrid lines 68 & 69 should be

```let row = Int(touch.y / (gp.size.height / CGFloat(rows) + 10))
 let column = Int(touch.x / (gp.size.width / CGFloat(cols) - 5 + 7))```

It is having trouble with padHeight and padWidth after rotation currently. That should solve your issue.

**Comment by NickCulbertson** [comment]
Actually it looks like this might already be fixed. Try updating to a newer AudioKitUI version.

**Comment by dpentecost** [comment]
Thanks Nick - I'll give it a try.

@dpentecost
Cell 646 704 2021

**Comment by dpentecost** [comment]
Okay, a little more information now: I did not change any code - keyboard
does not come up in Playgrounds on iPad when trying to change a package.
And since I just downloaded the app a couple of days ago, I think the
AudioKitUI code is the most recent (the lines in question are the same in
GitHub and my Playgrounds version, although line numbers are different). I
may be wrong about that.

But I found a workaround. Whatever orientation the app is started in, it
comes up with the same problem. But if I stop the running app (top right
orange Swift button) and then choose Restart instead of Stop in the popup,
it then runs as it should - targets all correct. This also works to correct
it if you change orientation while it is running.

In my opinion, the drumpad should be locked to landscape orientation anyway
(Playgrounds may not like this). Pads maintain their shape. There are other
music apps that do this, to keep the controls consistent. Thanks!

@dpentecost
Cell 646 704 2021

**Comment by dpentecost** [comment]
Update: Just deleted the apps in my Playgrounds, re-downloaded in case there were changes to AudioKitUI in the last day, and the situation is the same. Same workaround. FWIW I am running 15.3.1 on iPad Pro(9.7-inch)

**Comment by NickCulbertson** [comment]
The AudioKitUI version should be switched to “main”. You’ll need to remove the package from your build settings and re-import the swift package again, this time selecting main rather than a set release version number (there may be an easier way to do this). I’ll make a pull request next week updating the AudioKitUI version but in the meantime you can update the swift packages manually.

**Comment by dpentecost** [comment]
That did it. Although there is no way to set Main when you import it in Playgrounds. Shows latest versions and option to update to latest. Leaving it on the default v1.5 and reimporting worked. Now it has proper targets, re-orienting works.

Thanks for your quick response on this. Looking forward to exploring your other AudioKit repos!

**Comment by LorenAmelang** [comment]
Do we know why running this project in Playgrounds shows the screen rotation problem, but running the finished app I downloaded at the same time does not? The app works properly in any rotation.

**Comment by NickCulbertson** [comment]
I would assume it is because the app release version and the Playground version are using different AudioKitUI versions. TapCountingDrumPadGrid's touch logic is different between versions.

**Comment by aure** [comment]
Nick is right.
